services:
  - redis-server
before_install:
  - git submodule update --init --recursive
  - make qless-core
  - sudo apt-get install -y libevent-dev python-all-dev python3-all-dev
language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
install: pip install tox
script: tox
cache:
  directories:
    - .tox
    - $HOME/.cache/pip
